name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p "${{ secrets.DOCKER_PASSWORD }}"
      - run: docker build -t brianstaunton/docker-multi -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true brianstaunton/docker-multi npm test
 
      - run: docker build -t brianstaunton/multi-client ./client
      - run: docker build -t brianstaunton/multi-nginx ./nginx
      - run: docker build -t brianstaunton/multi-server ./server
      - run: docker build -t brianstaunton/multi-worker ./worker
 
      - run: docker push brianstaunton/multi-client
      - run: docker push brianstaunton/multi-nginx
      - run: docker push brianstaunton/multi-server
      - run: docker push brianstaunton/multi-worker
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env
          existing_bucket_name: elasticbeanstalk-us-east-1-838001772598
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
          use_existing_version_if_available: true
